Financial-Times/treecreeper

.circleci/config.yml, Makefile, package-lock.json, package.json
Gearing up to start publishing packages so we can start rolling out treecreeper packages
- enables `make npm-publish`
- creates db constraints before jest starts (to squish some race conditions in tests)
=> a few tweaks to test runs, and enable publishing

packages/tc-api-graphql/lib/get-augmented-schema.js, packages/tc-api-publish-adaptors/package.json, packages/tc-schema-sdk/data-accessors/__tests__/graphql-defs.spec.js, packages/tc-schema-sdk/data-accessors/graphql-defs.js
It was added to biz-ops-api, rather than schema, a while back when upgrading graphql-js, in order to avoid the api breaking (previous version included deprecated directive by default, new one needed it to be user defined). But this was never the right placce to store it
Prints the deprecated directive at the beginning of the graphQL that schema sdk generates.
=> move graphql deprecation directive into schema-sdk

packages/tc-schema-publisher/index.js, packages/tc-schema-publisher/scripts/deploy.js
This makes it possible for republishing to be more declarative, and easier to use in the gradual roll out of treecreeper things
schema publisher always reads from sdk to get its source data - does not accept a parameter which passes in some data
=> Fix so republishing always reads data from schema instance

packages/tc-api-db-manager/db-connection.js, packages/tc-api-rest-handlers/absorb.js, packages/tc-api-rest-handlers/lib/neo4j-model.js
In `absorb` handler, we should execute queries in a transaction in order to rollback the absorbed node and removed relationships
I add the `executeQueryWithTransaction` function and export it via `tc-api-db-manager`, and `tc-api-rest-handlers` use it.
In order to run multiple queries at once in same transaction scope, I declared `executeQueryWithTransaction()`  signature which accepts multiple query sets and return results as an array. see below of usage -- it is wrapped via `neo4j-model.js` to add biz ops enhancements.
```
// in tc-api-rest-handlers
const { executeQueryWithTransaction } = require('./libs/neo4j-model');
const transQueries = [
{ query: 'SOME DELETE QUERY', parameters: {...} },
{ query: 'SOME MERGE QUERY', parameters: {...} },
];
const [deleteResult, mergeResult] = …
```
=> Run absorb with transaction

packages/tc-schema-sdk/data-accessors/__tests__/graphql-defs.spec.js, packages/tc-schema-sdk/data-accessors/graphql-defs.js
accidentally already released e.g dependenciesREL to prod without intending to. Need to replace with something better ASAP, before anyone starts to query it
Switches REL suffix for _rel in rich relationship properties
=> change REL to rel in graphql

packages/tc-schema-sdk/data-accessors/__tests__/graphql-defs.spec.js, packages/tc-schema-sdk/data-accessors/graphql-defs.js
Schema currently supports
```
{
System(code: "biz-ops-api") {
name
dependencies_rel {
System {
code
}
}
}
}
```
but should support
```
{
System(code: "biz-ops-api") {
name
dependencies_rel {
from {
System {
code
}
}
}
}
}
```
Caused by missing quote marks in the schema, which surprisingly doesn't cause an error, just inaccurate augmentation of the schema
=> fix quotation mark bug in graphql

demo/api.js, demo/controllers/autocomplete.js
We can't use our production autocomplete endpoint to work on the relationship editor UI in this repo because the schema is not the same, so autocomplete would never retrieve any results
This implements a simple autocomplete endpoint within the demo app
=> created a simple autocomplete endpoint

packages/tc-ui/src/lib/mappers.js
I introduced a regression in tc-ui which meant the graphql queries used to build the admin UI have started fetching deprecated fields again
Filters them out before calling graphql
=> stop fetching deprecated fields for UI

packages/tc-ui/src/primitives/relationship/server.jsx
I accidentally dropped it in the move to tc-ui
Added sort to relationship component
=> reinstate sorting of relationships in UI

packages/tc-ui/src/primitives/boolean/server.jsx, packages/tc-ui/src/primitives/enum/server.jsx, packages/tc-ui/src/primitives/large-text/server.jsx, packages/tc-ui/src/primitives/number/server.jsx, packages/tc-ui/src/primitives/relationship/server.jsx, packages/tc-ui/src/primitives/temporal/server.jsx, packages/tc-ui/src/primitives/text/server.jsx
In bits of biz-ops-admin it's useful to know what kind of component we've been allocated in order to decide what data to pass in
Exposes the component name as a property of each component in tc-ui
=> expose component names

.circleci/config.yml, Makefile, packages/tc-markdown-parser/__tests__/property-value.spec.js, packages/tc-markdown-parser/lib/markdown-parser.js, packages/tc-markdown-parser/lib/tree-mutators/coerce-treecreeper-properties-to-type.js
We can't support any format of data we want to use in runbooks in the API and UI without also supporting it in the markdown parser. We recently added support for multiple choice enums to the API and UI, so here they are in markdown
Adds the ability for the enum coercer to parse items in a list
=> support multiple choice enums in markdown

packages/tc-markdown-parser/__tests__/first-paragraph.spec.js, packages/tc-markdown-parser/lib/tree-mutators/create-treecreeper-description-node.js
The current error has been reported as confusing
Changed the text. Note that this is on a branch forked from the last 0.3.x release. After releasing a tag on this branch I will merge back in to master
=> clearer error for multi paragraph descriptions in markdown

example-schema/relationships/CuriousSibling.yaml, example-schema/types/MainType.yaml, packages/tc-schema-validator/tests/type-test-suite.js
The validation rules for the schema did not match up with what values the libraries expect to find for the case of definig direction of reflexive rich relationships
- added an example reflexive rich relationship to the schema
- updated the schema validation tests to expect the right strings
=> Fix relationship schema validator

Makefile, demo/cms/index.jsx, example-schema/types/MainType.yaml, packages/tc-api-rest-handlers/__tests__/global-lock.spec.js, packages/tc-api-rest-handlers/lib/validation.js, packages/tc-schema-validator/MODEL_SPECIFICATION.md, packages/tc-schema-validator/tests/type-test-suite.js, packages/tc-ui/README.md, packages/tc-ui/src/lib/api-client.js, packages/tc-ui/src/lib/get-data-transformers.js, packages/tc-ui/src/pages/delete/__tests__/e2e-delete-record.cyp.js, packages/tc-ui/src/pages/edit/__tests__/e2e-edit-record.cyp.js, packages/tc-ui/src/pages/edit/template.jsx, packages/tc-ui/src/pages/view/__tests__/e2e-view-complete-record.cyp.js, packages/tc-ui/src/primitives/boolean/__tests__/e2e-record-boolean.cyp.js, packages/tc-ui/src/primitives/enum/__tests__/e2e-record-enum.cyp.js, packages/tc-ui/src/primitives/large-text/__tests__/e2e-record-large-text.cyp.js, packages/tc-ui/src/primitives/multiple-choice/__tests__/e2e-record-multiple-choice.cyp.js, packages/tc-ui/src/primitives/number/__tests__/e2e-record-number.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-create-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-delete-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-disply-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-edit-rich-relationships.cyp.js, packages/tc-ui/src/primitives/temporal/__tests__/e2e-record-temporal.cyp.js, packages/tc-ui/src/primitives/text/__tests__/e2e-record-text.cyp.js, packages/tc-ui/src/server.js, packages/tc-ui/src/test-helpers/cypress.js
GDPR hub have a requirement that some fields on systems relating to GDPR compliance should not be editable via the Biz Ops UI. So we need a mechanism to lock some fields for all records of a given type
- In the schema a field can have a `lockedBy` property, which lists all clients allowed to modify the field
- This is used to validate content submitted to the API
- This is also used to disable inputs in the UI
- Schema validation, api and UI e2e tests now exist for all 3
Also includes a little bit of housekeeping
- renames test-helpers/index.js to test-helpers/cypress.js
- removes the hard coding of the UIs client id as 'biz-ops-admin'
=> adds ability to lock a field globally

packages/tc-api-express/index.js, packages/tc-schema-sdk/README.md, packages/tc-schema-sdk/browser.js, packages/tc-schema-sdk/lib/__tests__/polling.spec.js, packages/tc-schema-sdk/lib/__tests__/stale.spec.js, packages/tc-schema-sdk/lib/__tests__/validate-code.spec.js, packages/tc-schema-sdk/lib/__tests__/validate-property-name.spec.js, packages/tc-schema-sdk/lib/__tests__/validate-property.spec.js, packages/tc-schema-sdk/lib/__tests__/validate-type-name.spec.js, packages/tc-schema-sdk/lib/updater.js, packages/tc-schema-sdk/sdk.js, packages/tc-schema-sdk/server.js, packages/tc-schema-validator/tests/enums.js, packages/tc-schema-validator/tests/primitive-types.js, packages/tc-schema-validator/tests/string-patterns.js, packages/tc-schema-validator/tests/type-hierarchy.js, packages/tc-schema-validator/tests/type-test-suite.js, packages/tc-schema-validator/tests/types.js
We had a 'fix what annoys you' tech debt day. It annoys me that teh schema-sdk was fussy about whether you've called `init()` before you call `ready()`. This sometimes leads to hard to track down bugs and test failures.
One of the objects the SDK is composed of is a schema updater, and the `ready()` method is just a proxy through to `this.updater.ready()`. But previously the updater was only created on `init()`, so if `ready()` was called before `init()` you'd get an error. this was a pain because the ready method on the updater was clever enough to handle these sorts of race conditions, just the proxying wasn't.
This PR moves creating the updater into the SDK constructor, and then does a bit of juggling to ensure initialisation only happens when needed. I think it's more or less as …
=> more sensible sdk initialisation

.stylelintrc.js, packages/tc-schema-sdk/package.json, packages/tc-ui/src/lib/components/buttons.jsx, packages/tc-ui/src/lib/components/input-wrapper.jsx, packages/tc-ui/src/lib/components/messages.jsx, packages/tc-ui/src/lib/components/structure.jsx, packages/tc-ui/src/main.css, packages/tc-ui/src/pages/edit/browser.js, packages/tc-ui/src/pages/edit/main.css, packages/tc-ui/src/pages/edit/template.jsx, packages/tc-ui/src/pages/view/browser.js, packages/tc-ui/src/pages/view/main.css, packages/tc-ui/src/pages/view/template.jsx, packages/tc-ui/src/primitives/relationship/__tests__/e2e-annotate-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-disply-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-edit-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/interface.spec.jsx, packages/tc-ui/src/primitives/relationship/lib/relationship.jsx, packages/tc-ui/src/primitives/relationship/lib/view-relationship.jsx, packages/tc-ui/src/primitives/relationship/main.css
Clean up following migration into treecreeper https://trello.com/c/yqI0yQ7Z/289-remove-all-references-to-biz-ops-from-treecreeper
Basic find and replace throughout tc-ui
Still need to build up a manual regression list from looking at all the changes. I'm boudn to have broken something.
Hopefully no difference
=> remove biz ops classes and data attributes

packages/tc-ui/src/pages/edit/template.jsx, packages/tc-ui/src/primitives/multiple-choice/server.jsx, packages/tc-ui/src/primitives/relationship/__tests__/e2e-annotate-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-edit-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/lib/relationship-picker.jsx, packages/tc-ui/src/primitives/relationship/lib/relationship.jsx, packages/tc-ui/src/primitives/relationship/lib/rich-relationship-properties.jsx, packages/tc-ui/src/primitives/relationship/main.css
[Improvements to rich relationship UX](https://trello.com/c/arkemHJ0/287-improvements-to-rich-relationship-ux)
Made the following changes based on the feedback we got
- the description I used for tests looks very long - what is your thought on that?
=> Improve ux

packages/tc-ui/src/lib/get-data-transformers.js, packages/tc-ui/src/pages/delete/__tests__/e2e-delete-record.cyp.js, packages/tc-ui/src/pages/edit/__tests__/e2e-edit-record.cyp.js, packages/tc-ui/src/pages/edit/template.jsx, packages/tc-ui/src/primitives/boolean/__tests__/e2e-record-boolean.cyp.js, packages/tc-ui/src/primitives/boolean/server.jsx, packages/tc-ui/src/primitives/enum/__tests__/e2e-record-enum.cyp.js, packages/tc-ui/src/primitives/large-text/__tests__/e2e-record-large-text.cyp.js, packages/tc-ui/src/primitives/multiple-choice/__tests__/e2e-record-multiple-choice.cyp.js, packages/tc-ui/src/primitives/number/__tests__/e2e-record-number.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-annotate-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-create-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-delete-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-disply-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-edit-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/lib/relationship-picker.jsx, packages/tc-ui/src/primitives/relationship/lib/relationship.jsx, packages/tc-ui/src/primitives/temporal/__tests__/e2e-record-temporal.cyp.js, packages/tc-ui/src/primitives/text/__tests__/e2e-record-text.cyp.js
We need to restore in-progress edit to relationships if form submission errors
- made `formDataToGraphQL` of get-data-transformers to call the parser with rel-props and component assigner function in case of relationships
- make relationship-picker component aware when a submission errors on the api
- added tests to validate the changes
- To be sure that all cypress setups/tests are run after the database in a new state, I wrapped every call to `resetDb` in cy.wrap ... following the discussion [here](https://github.com/cypress-io/cypress/issues/3172)
=> restore in-progress edits to relationships if form submission errors

packages/tc-markdown-parser/lib/tree-mutators/coerce-treecreeper-properties-to-type.js
In runbook.md, tc-markdown-parser@0.4.0 was failing a test. The test tested if, when a parse error happened, the error message contained the correct line numbers. However in order to generate the problem node (which is the mechanism to respond with multiple parse errors) the error must be manually caught and converted. In the refactor when supporting multiple choice enums I'd inadvertently added a potential error state I wasn't catching.
Covers the case when the heading of a field which is supposed to contain an enum (or multi enum) has no content beneath it - checks for the length of child nodes and converts to a problem immediately if there are no children
Note - there are _no_ tests for error states in this package. Given that user experience depends on us covering them carefully I …
=> fix bug detecting all error states for enum parser

packages/tc-ui/src/primitives/relationship/__tests__/e2e-annotate-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-disply-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/__tests__/e2e-edit-rich-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/lib/relationship.jsx, packages/tc-ui/src/primitives/relationship/lib/view-relationship.jsx, packages/tc-ui/src/primitives/relationship/main.css
We conducted a user testing for annotating relationships and this PR addresses some of the feedback we got
- replaced `Add|Edit annotations` with `Add|Edit details` - Edit page
- replaced `more info` with `view details` and `less` with `hide details` - View page
- added plus/edit icons on the annotation button
None
=> change annotation label to details and add icons

packages/tc-ui/src/server.js
v3.3.2 fixes a chrome bug, that chrome have now fixed themselves.
but 3.3.2 also broke the sticky save/cancel buttons
So pinning to a version where that still works
Longer term, v4.0.0 - where we're headed - supports stickiness in a better way, so can unpin then
=> pin o-layout to 3.3.1

packages/tc-ui/src/primitives/relationship/lib/view-relationship.jsx
- in Biz Ops admin some of the Report pages were broken (UNOWNED SYSTEMS, UNSUPPORTED SYSTEMS, UNDEFINED SYSTEMS)
- added check for relationship values
=> fix bug when value of relationship is null

packages/tc-ui/src/primitives/relationship/lib/view-relationship.jsx, packages/tc-ui/src/server.js
1. Since the new release, biz-ops-admin writes to api are not sending client id correctly
2. Inactive records are not hidden
1. Passes clientId into api client
2. Checks for inactiveness on the node not the relationship
=> Rollout bugfixes

.circleci/config.yml, packages/tc-ui/src/primitives/relationship/__tests__/e2e-delete-relationships.cyp.js, packages/tc-ui/src/primitives/relationship/lib/relationship-picker.jsx
@conor-mullen reported that any remove button on relationships was always removing the first one https://financialtimes.slack.com/archives/C07B3043U/p1584963133098000
Since adding additional buttons to the relationship interface the remove buttons' data attributes are now prefixed with `remove-`, which means some string manipulation needs to happen before using as an index value.
Also added a test to catch this case
=> fix removing child of index greater than 0

example-schema/relationships/OddThing.yaml, example-schema/type-hierarchy.yaml, example-schema/types/MainType.yaml, example-schema/types/OddCodeType.yaml, packages/tc-api-rest-handlers/__tests__/patch-relationship-create.spec.js, packages/tc-api-rest-handlers/lib/relationships/write.js
We'd never tried writing rich relationship props onto relationships to things with codes using symbols before. It didn't work. https://trello.com/c/DrJnmS07/313-cannot-write-rich-relationships-when-code-contains-special-characters
- Defines a new type that allows any string as a code in order to facilitate testing
- Takes a more aggressive approach to sanitising codes - only allows letters, digits and underscore
- Uses the index in the variable name in order to ensure uniqueness
=> Interesting related codes

packages/tc-api-db-manager/db-connection.js, packages/tc-api-rest-handlers/lib/metadata-helpers.js, packages/tc-api-rest-handlers/lib/neo4j-query-builder.js, packages/tc-api-rest-handlers/lib/relationships/write.js
Ingesting information connecting repositories to teams involved generating queries so slow and complex that when e.g. ingesting a team connected to 100's of repositories, the DB fell over 
I'm guessing the problem was the great number of `CASE` statements, a consequence of a couple of things
1. Not being able to tie a relationship effectively to the node it's related to, so when trying to target a relationship 'by code' it means filtering the entire result set each time rather than just iterating through each row once
2. Not being able to write an entire set of properties to an individual node retrieved from a larger result set - each property must be written individually, which means a CASE statement for each property. This applies to both metadata and custom properties
Well, it turns …
=> Avoid repetitive case statements in cypher

packages/tc-api-rest-handlers/lib/relationships/write.js
Regression caused by overzealous tidying of last PR
deletes code from props used to writ to relationships
=> avoid writing code onto relationships

.snyk, packages/tc-ui/src/lib/components/structure.jsx, packages/tc-ui/src/primitives/relationship/lib/view-relationship.jsx
-   In runbooks we want the link to the dependency/dependent to point to that system's runbook not biz-ops page
-  Passed a flag that can identify whether to point to the dependency/dependent runbook or biz-ops page when rendering the link to the dependency/dependent system.
My initial implementation was done by sending a href like `https://runbooks.in.ft.com/${encodeURIComponent(code)}` this can work for a single relationship but if there are more than one relationships this will not work as when we render the relationships, using the ViewComponent, we send an array of dependencies/dependents each with its own code.
=> for runbooks: set link to the dependency/dependent System point to its runbook not biz-ops page

demo/cms/components/subheader.jsx
- The current [implementation](https://github.com/Financial-Times/treecreeper/blob/303450a27da90afc9ef913f40c1397e33cd7f9cd/demo/cms/components/subheader.jsx#L3) of demo app's `Subheader` component is not working properly when we hookup treecreeper with Biz Ops. The reason for this is when we distructure properties form the prop `type` is undefined as it is not defined in the root but as
```
{
schema: {
type: "System"
...
}
}
```
-   replaced the `Subheader` component with the one that is implemented in Biz-ops-admin
=> fix demo app sub-header

packages/tc-api-graphql/lib/request-tracer.js
Request tracing has been broken for a while, which means we have zero visibility of which fields are safe to delete from GraphQL
Kiya found an interesting looking log https://trello.com/c/8annX6pE/2-comprehensive-graphql-tracing, which revealed that trying to do checks for deprecated fields on neo4j-graphql-js's generated types was causing errors to be thrown. This meant the entire trace for all types errored and we got no data.
This is now wrapped in a try catch, and trace logs are coming through:
=> fixed request tracing (I hope)

packages/tc-api-express/README.md, packages/tc-api-graphql/README.md, packages/tc-api-graphql/__tests__/graphql.spec.js, packages/tc-api-graphql/index.js, packages/tc-api-graphql/lib/get-apollo-middleware.js, packages/tc-api-graphql/lib/get-augmented-schema.js
-   Allow passing in extra resolvers and schema extensions as options in to [tc-api-graphql](https://trello.com/c/sWJrp982/282-allow-passing-in-extra-resolvers-and-schema-extensions-as-options-in-to-tc-api-graphql) 
-   added `options` argument 
```
{
...,
options: {
schema: [...],
resolvers: {...}
}
```
=> allow passing extra resolvers and schema extensions

README.md
-  You now need Node 12 to run this project
-   Updated the reference in the readme to Node 12 instead of Node 8
=> Update required node version to 12 in readme

packages/tc-markdown-parser/__tests__/nested-property-value.spec.js, packages/tc-markdown-parser/lib/parse-multiline-definition.js
To make relationship properties in runbook.md more legible, it's nice to add extra spaces in order to create line breaks. Unfortunately this leads to a different AST generated by the markdown parser, and therefore the parsing into properties on relationships broke (silently, I might add - the properties ended up getting completely discarded due to some quirk of the parser).
Takes a list of text - break - text - break - text nodes and compresses into a single text node where the value contains new lines. Part of me thinks it'd be more elegant to go the other way - take ones without line breaks and split them out into a tree that includes breaks before continuing with parsing. But that feels like it has potential to be an enormous yak shave.
It's worth noting that, in theory, the first node …
=> allow adding line breaks in nested propdefs

packages/tc-api-express/README.md, packages/tc-api-graphql/README.md, packages/tc-api-graphql/index.js, packages/tc-api-graphql/lib/get-apollo-middleware.js, packages/tc-api-graphql/lib/get-augmented-schema.js
If using a custom resolver to populate types they must be excluded from neo4j schema augmentation
Adds an option to be passed from tc-api-express down to tc-api-graphql. Also dedupes some README docs.
=> add ability to exclude types from neo4j augmentation

Makefile
Tasks were poorly organised. Also webpack had stopped running in watch mode locally because of some changes made to support cypress
- Reorders and groups into Install, Build & Test sections
- Documents what the various cypress tasks are used for
- Defines a new `run-app-biz-ops` task so we can use `concurrently` to run that task in parallel with webpack in watch mode
- _Hopefully_ doesn't break anything
=> Tidied makefile

example-schema/types/MainType.yaml, packages/tc-api-db-manager/__tests__/db-manager.spec.js, packages/tc-api-db-manager/index.js
To resolve [issue](https://github.com/Financial-Times/treecreeper/issues/206)
When running CALL db.indexes(); in neo4j only 23 are retrieved, but there should be many more, as stipulated by the use of canIdentify on properties in the schema.
In tc-api-db-manager only properties marked with unique are indexed... this should most likely be updated to go by canIdentify 
-   What's the main motivation of this work? bug fix
I added a condition for to check for canIdentify property. If this is present when unique is false the code marks this field for index creation. I have also updated the code to retrieve current indexes, if the index already exists nothing further will happen, if the index is not present a new index will be created for the field with canIdentify. 
When implementing I noticed …
=> Create index can identify

demo/cms/components/header.jsx, demo/cms/components/subheader.jsx, packages/tc-markdown-parser/docs/index.md
Runbooks is now on runbooks.ftops.tech, so I've updated the relevant links to the site
=> Update runbooks links to ftops.tech

.snyk, packages/tc-ui/src/lib/components/input-wrapper.jsx, packages/tc-ui/src/lib/markdown-to-html.js, packages/tc-ui/src/primitives/large-text/server.jsx
We appear to have `markdown` syntax in our biz ops schema field descriptions but we just display them as raw text.
Call `showdown` to convert field descriptions from markdown to html.
Untested - as `make install` for this monorepo isnt completing on my windows machine at the moment
Add any Screenshots or Images here to show any change/s
=> Enable markdown in the field descriptions!

package.json, packages/tc-api-rest-handlers/lib/events/__tests__/events-integration.spec.js, packages/tc-api-rest-handlers/lib/relationships/input.js, packages/tc-api-rest-handlers/patch.js
Since adding rich relationships to the model edits made in Biz Ops admin to systems have been causing excess update events in the kinesis stream.
After digging around quite a bit I discovered that the form was posting e.g `dependencies: [{code: 'abc', 'resiliencePatterns': null}]` when no relationship properties were added. The API was unable to tell that writing `null` to a previously undefined property had no effect, and instead thought this was a substantive change, causing an unnecessary write to the database and several change events in the kinesis stream.
- adds a test for this edge case
- explicitly handles the case where the existing property is not defined and a null value is sent, and treats this as 'no difference'
=> stop sending update events when noop deleted of relationship properties occur

demo/api.js, demo/cms/index.js, demo/cms/index.jsx
When getting Leanne and (IIRC) Kirsten onboarded I think they were both hit by problems connecting to the graphql explorer with no clear feedback on how to get unblocked.
- index page of the demo app links to the graphql explorer
- middleware always adds client id to api request made by the graphql explorer, so that the api does not error
- removed an old controller that was added to test some stuff out a while back but I don't think is useful any more
=> easier to get going with graphql explorer

.snyk, Makefile, example-schema/type-hierarchy.yaml, example-schema/types/FieldsetType.yaml, package.json, packages/tc-ui/src/lib/components/structure.jsx, packages/tc-ui/src/pages/edit/__tests__/e2e-create-type.cyp.js, packages/tc-ui/src/pages/edit/__tests__/e2e-edit-record.cyp.js, packages/tc-ui/src/pages/edit/template.jsx, packages/tc-ui/src/pages/view/template.jsx, packages/tc-ui/src/test-helpers/cypress.js
-  [ticket](https://financialtimes.atlassian.net/browse/RE-1844)
It’s possible to add a description for a fieldset in the schema but this isn’t used anywhere
We have made use of these within risk model 
- Created a new type in the demo schema `FieldsetType`
- add code to use the fieldset description on the edit and view pages
- added tests for create/view/edit  views to confirm fieldsets and description displays as expected. 
n/a
=> Add fieldset description

example-schema/type-hierarchy.yaml, example-schema/types/ValidatedType.yaml, packages/tc-api-rest-handlers/__tests__/patch-create.spec.js, packages/tc-api-rest-handlers/lib/validation.js
@nl-ria  found a bug whereby empty strings in fields that used a vaildation pattern were being rejected. This is because the pattern was running against all strings, even empty ones.
Adds a test and coerces empty strings to null early. Empty strings are already treated as (or are supposed to be, at least) null when writing to the database, so this shifts that coercion earlier in order to skip validation.
Similar thing needs to happen for properties on relationships - i will add an issue to capture that requirement, but won't tackle it here because it'll get way more complicated and does not actually apply to any of our Biz Ops data at the moment - we have no string-validtead properties written onto relationships
I do now wonder if there's been a bug for a while that means we've been …
=> prevent blocking of empty strings by validation patterns

packages/tc-ui/src/primitives/relationship/lib/relationship-picker.jsx
When e.g. adding system dependencies to a system we want to avoid something being a dependency of itself, so we filter out suggestions with the same code as the current record.
_But_ this meant that if adding record of typeA to a record of typeB, but they both had the same code, then the suggestion would be filtered out, and the relation souldn't be created
Checks for type as well as code identity
=> avoid being unable to suggest items with same code

packages/tc-ui/src/primitives/number/__tests__/e2e-record-number.cyp.js, packages/tc-ui/src/primitives/number/server.jsx
-   [ticket](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1169&projectKey=RE&modal=detail&selectedIssue=RE-1852)
-   if you save the form for a risk with empty strings in the number fields, they get saved as zeros. 
expected behaviour - save as null
-   Updated number parser to check for empty string, and if so return null entry to be sent to treecreeper API 
-   End user expected behaviour of this is that these fields will not display on success screen. Added test to replicate this. 
Mention here sections of code which you would like reviewers to pay extra attention to, for example:
_I have made a few assumptions here - there may be edge cases or further places this needs updating_
=> fix empty input for int type should defaulting to 0 

package.json, packages/tc-ui/src/pages/edit/template.jsx
@wheresrhys reported that https://biz-ops-test.in.ft.com/System/sso-subscription-service-my-licence/edit was returning a 503.  Based on the logs in splunk, this was caused by a 413 entity too large error.  According to [the AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html), the limit payload limit for lambdas is 6MB
For this particular system (at least based on data in test) we're returning a payload of 11.4MB
This looks to be caused by each base64 encoded image included in troubleshooting section being output in the payload 20 times.
Rather than outputting the entire biz-ops record as a json-encoded attribute for every component, output the same structure, but truncate any large strings at the top level
This isn't the nicest solution, but as I'm not …
=> Truncate strings

example-schema/types/MainType.yaml, packages/tc-schema-sdk/README.md, packages/tc-schema-sdk/data-accessors/__tests__/type.spec.js, packages/tc-schema-sdk/data-accessors/type.js, packages/tc-schema-validator/tests/type-test-suite.js, packages/tc-ui/src/lib/get-schema-subset.js, packages/tc-ui/src/lib/mappers/graphql-query-builder.js
The UI breaks when properties make use of the powerful @cypher directive. There's another PR to sketch out what being able to display these properties in the UI might look like https://github.com/Financial-Times/treecreeper/pull/256...
But I realised that is quite a big job, and using @cypher is useful now (in particular for distilling risk blast radiuses down into summaries, or extracting other useful summaries from the new more ophisticated modelling we're doing of prosucts, capabilities, Fastly, Hosts etc).
So this PR implements the relatively small chaneg of suppressing any attempt to render these fields in the admin UI, saving them for the GraphQL api alone. This means we can define them and explore using them, then take on the UI job as and when it feels useful to do so
- Adds a new …
=> avoid outputting cypher properties in the ui

packages/tc-ui/src/pages/edit/handler.js, packages/tc-ui/src/pages/edit/template.jsx
Still a bug where biz ops pages with large images embedded bust the lambda payload limit despite trimming strings
Because the form is broken into fieldsets each fieldset was only shrinking down the size of the one or tow fields that appeared in it. This PR does it once a t the root level and passes the smaller object down the tree
=> reduce size of documents once at the root level

packages/tc-ui/src/pages/edit/browser.js, packages/tc-ui/src/pages/edit/handler.js, packages/tc-ui/src/pages/edit/template.jsx, packages/tc-ui/src/primitives/relationship/browser.jsx
Fixes #267 - this is having user impact surprisingly quickly
- Sets the entire record as a property of the entire form
- Passes that in to the component on the client side (need to use render rather than hydrate as the component now has extra props on the client side so hydrate moans about the data not matching)
- Stops passing entire record into individual primitive components on the server side (aside from `AdditionalEditComponent` which the user may set - it'd be a breaking change to remove from there)
- stop creating a truncated version of the record to send to the client - now it's only a single copy we will not breach the payload limit
=> only send json copy of record once to the browser

package.json, packages/tc-api-db-manager/db-connection.js, packages/tc-api-db-manager/package.json, packages/tc-api-rest-handlers/__tests__/patch-diff.spec.js, packages/tc-api-rest-handlers/__tests__/patch-field-locking.spec.js, packages/tc-api-rest-handlers/__tests__/patch-update.spec.js, test-helpers/db-spies.js
https://github.com/neo4j/neo4j-javascript-driver/issues/606
Being a bit more careful when awaiting db results in the code path taken during tests (which do not apply a timeout).
=> attempt to fix bug in use of neo4j-driver

packages/tc-api-graphql/__tests__/graphql.spec.js, packages/tc-api-graphql/lib/get-augmented-schema.js, packages/tc-api-graphql/package.json
Currently if you add a customer resolve to a Type which has any document fields, the document resolvers get removed.
Using lodash's merge function to deep merge the resolvers objects, rather than the shallow Object.assign.  This enables both sets of resolvers to exist side-by-side.
=> Allow custom resolver to co-exist with document resolver

packages/tc-ui/src/primitives/relationship/server.jsx
For the first time we have examples of records that have a temporal field in heir summaries (Incidents with their start dates). The UI breaks for records related to these records because the query to generate the relationships is constructed from invalid fragments
For temporal types, request `{formatted}`
=> Related dates

packages/tc-schema-sdk/data-accessors/__tests__/graphql-defs.spec.js, packages/tc-schema-sdk/data-accessors/graphql-defs.js
To avoid this sort of thing https://github.com/Financial-Times/biz-ops-schema/pull/281/files#diff-4f26967fe0a45c699d6bd9b23c4f0660R239-R252
Escapes quotes and new lines in the cypher statement and adds a test
=> allow cypher properties in schema to be multiline

.github/.github/workflows/sync-labels.yaml
https://rer.in.ft.com, for prioritising issues, is powered by every repo having the same labels. This PR adds the github action that syncs labels to the standard rel-eng set.
Adds the github action file for Financial-Times/rel-eng-labels
=> Add sync-labels github workflow

packages/tc-ui/src/primitives/temporal/__tests__/e2e-record-temporal.cyp.js, packages/tc-ui/src/primitives/temporal/server.jsx
oggy from membership found a bug when trying to update a record https://financialtimes.slack.com/archives/C0LJJ8UUX/p1604580902010800?thread_ts=1604313376.413800&cid=C0LJJ8UUX
After some investigation I found that if a record contains some already populated temporal fields, but something else causes an error in form submission, then when the form is rerendered those temporal values are lost
When rendering the form originally using GraphQL data the values are of the form `myDate: formatted: 'An ISO string'}`. But when submitting the form the data is converted to `myDate: 'An ISO string'` (which is what the REST api expects). After an error this data is passed back to the form to render and the component previously foudn there was no `formatted` property and therefore treated it as `null`. …
=> fix redisplay of temporal fields on edit page after bad form submission

packages/tc-api-graphql/lib/get-augmented-schema.js
When adding custom resolvers that traverse nested objects (e.g. in SOS) the absence of a property typically means just return `null`, but while this does resolve to `null` it also triggers the following ugly error:
```
{
"message": "Resolve function for \"SOSV1Facets.dataRecovery\" returned undefined",
"locations": [
{
"line": 6,
"column": 5
}
],
"path": [
"System",
"sosV1",
"facets",
"dataRecovery"
],
"extensions": {
"code": "INTERNAL_SERVER_ERROR"
}
}
```
Use the graphql option to suppress these errors. It's a global option which I feel a bit uncomfortable with, but if we find it useful to re-enable in future we can do so, and implement suppression rules in the places we do want them
=> Allow undefined in resolve

packages/tc-ui/src/pages/edit/browser.js
Fixes #195
Fixes https://github.com/Financial-Times/biz-ops-admin/issues/532
Treats string values of 'null' as empty. (Some previous change evidently meant null is now output instead of undefined/''.
=> fix MVP submit prevention

packages/tc-api-rest-handlers/README.md, packages/tc-api-rest-handlers/__tests__/delete.spec.js, packages/tc-api-rest-handlers/delete.js, packages/tc-api-rest-handlers/lib/events/__tests__/events-integration.spec.js, packages/tc-api-rest-handlers/lib/events/index.js, packages/tc-api-rest-handlers/lib/events/related-events.js, packages/tc-api-rest-handlers/lib/relationships/input.js
Long standing need to be able to delete records with relationships for managing data in bulk importers, and for easy cleanup of records that no longer need to exist.
- Adds a `force=true` option to DELETE requests
- updates the events implementation to send update events for any related systems
=> implement force delete in the API

packages/tc-ui/src/lib/components/input-wrapper.jsx, packages/tc-ui/src/primitives/boolean/server.jsx
Fixes https://github.com/Financial-Times/biz-ops-admin/issues/444
Prepends `id-` to `for` attributes
=> fix accessibility of form inputs

packages/tc-schema-sdk/README.md, packages/tc-schema-sdk/lib/raw-data-wrapper.js
Difficult to debug when a method is being called before the schema is ready
- updates out of date docs in the message
- explicitly calls out the 'using in the top level of a module' antipattern
=> clearer message for schema doesn't exist error

packages/tc-api-rest-handlers/__tests__/document-store.spec.js, packages/tc-api-rest-handlers/lib/separate-documents-from-body.js, packages/tc-api-s3-document-store/__tests__/s3-docstore-patch.spec.js, packages/tc-api-s3-document-store/patch.js
Biz Ops could not unset any strings stored in Document properties
Fixes https://github.com/Financial-Times/biz-ops-admin/issues/548
- There was some code explicitly preventing passing empty strings to the s3 document store. While this has good intentions - don't want to create documents when we have no data to write - it's premature and means that those empty properties don't get through to the docstore in situations where the user wants to delete something. This code has been removed and the test updated to expect that a null gets passed through
- Diffing logic in the docstore has been updated to avoid deciding a write is needed when comparing `null` (from the API) with `undefined` (from S3), 
- Before writing to S3 the docstore deletes any falsy values from the body, which effectively …
=> delete properties rather than storing empty strings

packages/tc-api-express/__tests__/schema-polling-startup.spec.js, packages/tc-api-express/__tests__/schema-polling-updates.spec.js, packages/tc-schema-publisher/scripts/__tests__/deploy-test.spec.js, packages/tc-schema-publisher/scripts/__tests__/schema/enums.yaml, packages/tc-schema-publisher/scripts/__tests__/schema/type-hierarchy.yaml, packages/tc-schema-publisher/scripts/__tests__/schema/types/TypeA.yaml, packages/tc-schema-publisher/scripts/__tests__/schema/types/TypeB.yaml, packages/tc-schema-publisher/scripts/command.js, packages/tc-schema-publisher/scripts/deploy.js, packages/tc-schema-sdk/README.md, packages/tc-schema-sdk/__tests__/test-schema-properties.spec.js, packages/tc-schema-sdk/data-accessors/__tests__/types.spec.js, packages/tc-schema-sdk/lib/raw-data-wrapper.js, packages/tc-schema-sdk/sdk.js, packages/tc-schema-validator/MODEL_SPECIFICATION.md, packages/tc-schema-validator/validation/json-schema/enums.js, packages/tc-schema-validator/validation/json-schema/type.js
2 motivations:
- be able to publish a schema change to test without a risk of it getting to prod, while having it persist reliably in test
- be able to add test definitions to the schema that can be used for writing comprehensive tests of various bits of the ecosystem (in particular UI components)
Various aspects of the schema (types, enums, properties, ...) may have an `isTest: true` property. 
The schema SDK can be initialised with an `includeTest` flag. If false these test types are stripped out.
This option can be set by `tc-schema-publisher` as a command line argument
Thus a single schema can be authored to include test elements and published with the flag set to `true` to the test environment and with the flag set to `false` for the prod environment.
The workflow for trying out …
=> Allow setting some schema parts as 'test only'

packages/tc-schema-sdk/__tests__/test-schema-properties.spec.js, packages/tc-schema-sdk/sdk.js
Testing out in Biz Ops Admin locally I found that despite the test properties being defined in the test schema, these were being stripped out by the app when using the latest schema SDK - not what we ant at all!
Tweaked the config so that
- including test properties defaults to _true_ in the SDK (used by apps) so in test apps no test schema properties get stripped out
- including test properties remains unchanged, still defaulting to _false_, so that we don't accidentally publish test schema bits and pieces to prod
=> avoid removing test properties from schema in test apps

packages/tc-schema-validator/validation/json-schema/references.js, test-helpers/test-fixtures.js
Addressing this issue: https://github.com/Financial-Times/treecreeper/issues/362
Changes the regex matcher for systemCodes from `^[a-z][\\-a-z]+[a-z]$` to `^[a-z][a-z0-9-]+[a-z0-9]$`
=> fix: regex matcher for SystemCodes

packages/tc-api-rest-handlers/README.md, packages/tc-api-rest-handlers/__tests__/patch-efficient.spec.js, packages/tc-api-rest-handlers/__tests__/patch-properties.spec.js, packages/tc-api-rest-handlers/get.js, packages/tc-api-rest-handlers/lib/diff-properties.js, packages/tc-api-rest-handlers/lib/neo4j-query-builder.js, packages/tc-api-rest-handlers/lib/neo4j-type-conversion.js, packages/tc-api-rest-handlers/lib/read-helpers.js, packages/tc-api-rest-handlers/lib/relationships/input.js, packages/tc-api-rest-handlers/patch.js, test-helpers/test-fixtures.js
Fixes this https://github.com/Financial-Times/biz-ops-api/issues/534
When fetching data from the database (both the preflight request for diffing and the final response to user) only retrieves relationships relevant to the current request
=> Implement option to make writes more efficient
